//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlockIt_ShareAndCharge.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlockIt_ShareAndCharge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;db&quot;,                       &quot;constant&quot;: true,   &quot;inputs&quot;:[],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;getContractType&quot;,          &quot;constant&quot;: true,   &quot;inputs&quot;:[{&quot;name&quot;:&quot;_poleID&quot;,&quot;type&quot;:&quot;bytes32&quot;},{&quot;name&quot;:&quot;_user&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;outputs&quot;:[{&quot;name&quot;:&quot;ctype&quot;,&quot;type&quot;:&quot;uint8&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;libManager&quot;,               &quot;constant&quot;: true,   &quot;inputs&quot;:[],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;ad [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AbiChargePolesJson {
            get {
                return ResourceManager.GetString("AbiChargePolesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;mobilityTokenLib&quot;,       &quot;constant&quot;: true,   &quot;inputs&quot;:[],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;feeManagementLib&quot;,       &quot;constant&quot;: true,   &quot;inputs&quot;:[],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;priceProviderLibs&quot;,      &quot;constant&quot;: true,   &quot;inputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;uint256&quot;}],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AbiMainLibJson {
            get {
                return ResourceManager.GetString("AbiMainLibJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;totalSupply&quot;,                &quot;constant&quot;: true,   &quot;inputs&quot;:[],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;uint256&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;getWhitelist&quot;,               &quot;constant&quot;: true,   &quot;inputs&quot;:[{&quot;name&quot;:&quot;_user&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;bool&quot;}],&quot;payable&quot;:false},
        ///  { &quot;type&quot;: &quot;function&quot;,    &quot;name&quot;: &quot;db&quot;,                         &quot;constant&quot;: true,   &quot;inputs&quot;:[],&quot;outputs&quot;:[{&quot;name&quot;:&quot;&quot;,&quot;type&quot;:&quot;address&quot;}],&quot;payable&quot;:false},
        ///  { &quot;typ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AbiMobilityJson {
            get {
                return ResourceManager.GetString("AbiMobilityJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Link_16x {
            get {
                object obj = ResourceManager.GetObject("Link_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restart_16x {
            get {
                object obj = ResourceManager.GetObject("Restart_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SlockIt {
            get {
                object obj = ResourceManager.GetObject("SlockIt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
